services:
  # LA BASE DE DONNÉES
  database:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=prefect
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=prefect
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - prefect-network
  
  server:
    image: prefecthq/prefect:3-latest
    restart: always
    volumes:
      - prefect_data:/root/.prefect
    entrypoint: ["prefect", "server", "start"]
    environment:
      # Connection DB
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://prefect:${POSTGRES_PASSWORD}@database:5432/prefect
      # Autorise le serveur à écouter toutes les interfaces réseau du conteneur (extérieur au conteneur)
      - PREFECT_SERVER_API_HOST=0.0.0.0
      # 127.0.0.1 pointait vers le conteneur lui-même, pas le serveur Prefect
      - PREFECT_API_URL=http://server:4200/api
      # L'URL que l'UI utilisera
      - PREFECT_UI_API_URL=http://localhost:4200/api
    ports:
      - "4200:4200"
    depends_on:
      - database
    networks:
      - prefect-network
  
  # MinIO — хранилище моделей
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data       # persistent storage
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    networks:
    - prefect-network

  # MLflow — каталог моделей (Model Registry)
  mlflow:
    image: ghcr.io/mlflow/mlflow
    container_name: mlflow
    environment:
      MLFLOW_TRACKING_URI: ${MLFLOW_TRACKING_URI}
      MLFLOW_S3_ENDPOINT_URL: ${MLFLOW_S3_ENDPOINT_URL}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    ports:
      - "5000:5000"
    command: >
      mlflow server
        --backend-store-uri sqlite:///mlflow.db
        --default-artifact-root s3://mlflow/
        --host 0.0.0.0
        --allowed-hosts "mlflow:*, localhost:*, minio:*"
    depends_on:
      - minio
    networks:
    - prefect-network

  flow:
    build: ./flow
    image: hannakiyk/ml_factory-flow
    environment:
      PREFECT_API_URL: http://server:4200/api
    depends_on:
      - server
      - minio
      - mlflow 
  api:
    build: ./src/api
    environment:
      MLFLOW_TRACKING_URI: ${MLFLOW_TRACKING_URI}
      MLFLOW_S3_ENDPOINT_URL: ${MLFLOW_S3_ENDPOINT_URL}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      API_PORT: ${API_PORT}
    ports:
      - "${API_PORT}:${API_PORT}"
    
    depends_on:
      - mlflow

  front:
    build: ./src/front
    environment:
      API_HOST: ${API_HOST}
      API_PORT: ${API_PORT}
      FRONT_PORT: ${FRONT_PORT}
    ports:
      - "${FRONT_PORT}:${FRONT_PORT}"
    depends_on:
      - api


networks:
  prefect-network:
    driver: bridge

# Persistent volumes
volumes:
  minio_data:
  db_data:
  prefect_data: